# https://github.com/awslabs/serverless-application-model/blob/develop/versions/2016-10-31.md
# Indentation needs to be set with spaces, because YAML...
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API for user profile

Resources:
    UpdateProfileFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: update-profile.default
            # Runtime: nodejs8.10
            Runtime: nodejs16.x
            Timeout: 1000
            ReservedConcurrentExecutions: 5
            MemorySize: 256 # Need to increase the memory to go faster and avoid the 30s timeout on the API gateway
            CodeUri: ./dist/update-profile
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - AmazonSESFullAccess
                - SecretsManagerReadWrite
                # - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: api-update-profile
            AutoPublishAlias: live
            FunctionUrlConfig:
                AuthType: NONE
